### ISSUE TITLE
Add Missing Method for Topics

### ISSUE THREAD

**Issue by nabinbhatt** [novuhq/novu-python#133]
Method to Delete a topic is missing and can't be hit from this SDK.
https://api.novu.co/api#/Topics/TopicsController_deleteTopic

**Comment by sumitsaurabh927** [comment]
@nabinbhatt Would you like to work on it?

**Comment by nabinbhatt** [comment]
Yes you can assign me @sumitsaurabh927

**Comment by sumitsaurabh927** [comment]
here: https://github.com/novuhq/novu-python/pull/134
