### ISSUE TITLE
FEATURE:  Utils to generate an iterator on pagination DTO

### ISSUE THREAD

**Issue by ryshu** [novuhq/novu-python#14]
It would be great if from a PaginatedNotificationTemplateDto you could access the previous/next pages with just a PaginatedNotificationTemplateDto.get_next_page().

And the same with the other paginated views

Or let list behave similarly to list on non-paginated routes, and make requests as the iterator is consumed.

**Comment by ryshu** [comment]
Hi @unicodeveloper,

Actually, I don't even know if the feature would be useful for users.
I'm waiting to see requests on this point before implementing something that nobody would use.

**Comment by unicodeveloper** [comment]
I am on discord, and about two to three folks have mentioned something like this. So it will be great for it to be worked on @ryshu

**Comment by ryshu** [comment]
Part of https://github.com/novuhq/novu-python/tree/v1.5.0, should be reused when the API will be completely standardized on other methods.

An issue to address the provision of stream options by API should be opened to organize
