### ISSUE TITLE
Can't add data field to subscriber

### ISSUE THREAD

**Issue by elmehalawi** [novuhq/novu-python#196]
**Describe the bug**
The `SubscriberDto` class seems to be missing the `data` field. 

**To Reproduce**

The following script should reproduce the issue:

```python3
from novu.dto.subscriber import SubscriberDto

# Define a subscriber instance
subscriber = SubscriberDto(
    email="email@example.com",
    subscriber_id="laiwjfalwijfalwiefjawifj",
    first_name="Hassan",
    last_name="M",
    data={ # No parameter named "data"
        'has_account': False,
        'replied': False,
    },
)
```

When run, you get:

```
Traceback (most recent call last):
  File "/Users/hassan/Documents/novu/import-subscribers.py", line 4, in <module>
    subscriber = SubscriberDto(
                 ^^^^^^^^^^^^^^
TypeError: SubscriberDto.__init__() got an unexpected keyword argument 'data'
```

**Expected behavior**
The docs say you can add custom user properties in a "data" field. I expected this to work in python using a string->string dictionary. Please correct me if I've made a bad assumption.

**Versions (please complete the following information):**
 - Novu version: (whatever is currently in production idk)
 - Python version: 3.11
 - Novu-python version: 1.11.0

**Comment by ryshu** [comment]
Ok in https://github.com/novuhq/novu-python/releases/tag/v1.13.0
