### ISSUE TITLE
Missing Workflow creation guide for python

### ISSUE THREAD

**Issue by flczin** [novuhq/novu-python#207]
There is no information on how to create workflows via python SDK on the documentation.

**Comment by ryshu** [comment]
Hi @flczin

We are dealing with this subject in several issues:

* https://github.com/novuhq/novu-python/issues/92
* https://github.com/novuhq/novu-python/issues/69
* https://github.com/novuhq/novu-python/issues/186
* https://github.com/novuhq/novu-python/issues/13

Without these different treatments, no guide will be able to clearly describe how to create a workflow from APIs.

FYI, we (in my company) currently use YAML files with the complete description of our workflow to automate environment declarations. The latter is converted into JSON content and we use the NotificationTemplate API to create or modify them.
