### ISSUE TITLE
IntegrationApi.create fails when using CHAT channel

### ISSUE THREAD

**Issue by cedric-fauth** [novuhq/novu-python#21]
**Describe the bug**

When trying to create any chat integration (which does not require credentials like msteams, discord etc.) the request was made successfully but the response does not contain a `credentials` field. This results in an error because the response cannot be parsed correctly to `IntegrationDto` I think:

```bash
Traceback (most recent call last):
  File "novu_test/demo_workflow.py", line 67, in <module>
    msteams_integration = integration_api.create(
  File "/home/node/.local/lib/python3.9/site-packages/novu/api/integration.py", line 52, in create
    return IntegrationDto.from_camel_case(self.handle_request("POST", self._integration_url, payload)["data"])
  File "/home/node/.local/lib/python3.9/site-packages/novu/dto/base.py", line 71, in from_camel_case
    return cls(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'credentials'
```

**To Reproduce**

Call `IntegrationApi.create` with `channel="chat"`: 
```python
msteams_integration = integration_api.create(
    dto.IntegrationDto(
        channel=Channel.CHAT.value,
        provider_id=ChatProviderIdEnum.MS_TEAMS.value,
        active=True,
        credentials={},
    )
)
``` 

**Expected behavior**
Should return a `IntegrationDto` object.

**Versions (please complete the following information):**
 - Python version 3.9.2
 - Novu-python version 1.1.0

**Comment by ryshu** [comment]
Hi @cedric-fauth,

Thank you for this report, I think #29 will solve your problem.

**Comment by ryshu** [comment]
@cedric-fauth  Available in https://pypi.org/project/novu/1.2.1a1/. Can you test that it solves your problem?

**Comment by cedric-fauth** [comment]
Hi, sorry but currently I am not able to test this.
