### ISSUE TITLE
Error in CI/CD -> Fail to publish new versions after a policy update

### ISSUE THREAD

**Issue by ryshu** [novuhq/novu-python#228]
Hi @unicodeveloper,

It seems that after a change to the rules on your Git repositories, the semantic-release bot is no longer able to push commits that tag versions.

See logs here:

![image](https://github.com/novuhq/novu-python/assets/22155261/474bd43f-5362-4d4b-b80e-b50fc5098db2)

https://github.com/novuhq/novu-python/actions/runs/7868653993/job/21466246462

**Comment by unicodeveloper** [comment]
@ryshu What do I need to do here to ensure this works?

**Comment by ryshu** [comment]
@unicodeveloper Hum, I think this box is checked:

![image](https://github.com/novuhq/novu-python/assets/22155261/885ca630-ac80-4174-b8ca-f50c421ca7e2)

**Comment by unicodeveloper** [comment]
Oh yes, I see. Okay, I'll update that now @ryshu

**Comment by unicodeveloper** [comment]
@ryshu please can you try again now. I have updated it.

**Comment by ryshu** [comment]
If it's not that, it's probably the token in the environment variables that has expired

To recreate a token, you must give it the following rights: https://github.com/semantic-release/github/issues/175#issuecomment-484964034

**Comment by ryshu** [comment]
Ok for me: https://github.com/novuhq/novu-python/commit/7cd4f85e62d1d410c30019179cc61e3a5b316d73

Do not forget to take a look at ALPHA pull request ;)

https://github.com/novuhq/novu-python/pull/187
