### ISSUE TITLE
Write an Article about Novu Python SDK and highlight a few features

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-python#24]
Hey @ryshu would you like to write an article about novu python SDK?

Basically an article that does the following:

- Introduces Novu Python SDK to the public
- Highlight certain features
- Share your own experience
- Conclusion.

I'll be happy to help review and edit. 

WDYT?

**Comment by ParthNarkhede** [comment]
Hey! I want to contribute by writing an article about it..

**Comment by ryshu** [comment]
Hey @ParthNarkhede, it could be a great idea and contribution.

I took time to initiate the package but the integration has been delayed in my company and I don't have too much to say about it.

@unicodeveloper WDYT ?

**Comment by unicodeveloper** [comment]
Yes please. @ParthNarkhede please go ahead. What will you need?

Btw, we are currently writing quickstart guides for all of our SDK. We need already have a format that will be uploaded this week. 

Is this something you will be open to contributing to? @ParthNarkhede or even @ryshu ?

**Comment by ryshu** [comment]
For the time being, I prefer to stay in retreat on the writing.

I prefer to take and process the tickets that have been opened to unlock the first users because I already write documents for work.

**Comment by unicodeveloper** [comment]
Alright, no problem

**Comment by kunjshukla** [comment]
@unicodeveloper Can u assign me this issue..?

**Comment by unicodeveloper** [comment]
@kunjshukla yes, you are assigned to this issue now.

**Comment by unicodeveloper** [comment]
@kunjshukla Any update here? How are we looking so far?

**Comment by kunjshukla** [comment]
@unicodeveloper working on it, got some urgent work It'll be done in 2 days at max.

**Comment by unicodeveloper** [comment]
Alright thanks. Looking forward to it @kunjshukla

**Comment by kunjshukla** [comment]
@unicodeveloper the article is ready. 
Where should do I do the PR..?

**Comment by unicodeveloper** [comment]
@kunjshukla The article should be on Dev.to or hashnode. But you can submit a PR where I can go through and help review.

**Comment by ryshu** [comment]
Where are we with this issue, I think we can close it? @unicodeveloper

**Comment by unicodeveloper** [comment]
Yeah we can close it
