### ISSUE TITLE
Add retry option

### ISSUE THREAD

**Issue by chris-stetter** [novuhq/novu-python#25]
**Is your feature request related to a problem? Please describe.**
When an http error is returned (e.g. 502), there is currently no retry.

**Describe the solution you'd like**
The used `requests` package offers native retry logic, which would be great to set globally or on the API level.

**Describe alternatives you've considered**
Putting all API calls into a try and except and handle it yourself, but will bloat code.

**Comment by ryshu** [comment]
Hi @chris-stetter,

I did some research following your issue focusing on the idea of keeping the Novu package logic as simple as possible.

I imagine that by talking about the native implementation of the `requests` module of the retry part, you're talking about the idea of allowing users to provide us with a session prepared by themselves:

https://stackoverflow.com/questions/23267409/how-to-implement-retry-mechanism-into-python-requests-library

Following this idea, I think we can easly provide something like this:

```python
from requests import Session
from requests.adapters import HTTPAdapter, Retry

from novu.api import EventApi

session = Session()
retries = Retry(total=5, backoff_factor=1, status_forcelist=[ 502, 503, 504 ])
session.mount('http://', HTTPAdapter(max_retries=retries))

event_api = EventApi("https://api.novu.co/api/", "<NOVU_API_TOKEN>", session=session)
event_api.trigger(
    name="<YOUR_TEMPLATE_NAME>",
    recipients="<YOUR_SUBSCRIBER_ID>",
    payload={},  # Your Novu payload goes here
)
```

On the one hand, this allows the user to configure the entire session for advanced cases, while on the other we keep the package simple and easy to use.

WDYT ?

**Comment by chris-stetter** [comment]
That is a great idea and would fit our use case very well!

**Comment by ryshu** [comment]
Great, it seems simple enough to implement in the lib. I'll add it to the next release.

FYI @unicodeveloper
