### ISSUE TITLE
Change subscriber preferences not possible with current logic

### ISSUE THREAD

**Issue by torestenbock** [novuhq/novu-python#26]
**Describe the bug**
Notification templates in our system has all channels preferences set to off initially and the intention is to change this as they are adding push_tokens/emails/etc in the onboarding flow. But it fails using this package to make the subsciber preferences changes. The "channel" argument for `subscribers.change_channel_preferences` takes a `Channel` enum type. However, when calling this as intended it fails with "TypeError: Object of type Channel is not JSON serializable". The Novu API Swagger states a `string` but when calling `Channel.PUSH.value` it returns 400 Bad Request. 

Not sure how to approach this problem. Looking at the [Swagger](https://api.novu.co/api#/Subscribers/SubscribersController_updateSubscriberPreference) it seems the paylod that is `PATCHed` is not correct, it is missing some values in the schema (particularly the dual `enabled` args).

**To Reproduce**
1. Install the `novu` package
2. Add a subscriber
3. Call `subscribers.change_channel_preferences` 

**Expected behavior**
Return success when changing a subscriber preference.

**Versions (please complete the following information):**
 - Novu version: Hosted version
 - Python version: 3.11.2
 - Novu-python version: 1.2.0

**Additional context**
If it is as easy as changing [`{"channel": {"type": channel, "enabled": channel_enabled}}`](https://github.com/novuhq/novu-python/blob/7ef9f35b4cc9bc9b8f5812c4b1781345d908f2e0/novu/api/subscriber.py#LL165C17-L165C75) to `{"channel": {"type": channel.value, "enabled": channel_enabled}}` I don't mind creating a PR to do that. But I want to hear with this community on any second opinions as I think the missing `enabled` in the root of the object also needs to be fixed?

**Comment by ryshu** [comment]
Hi @torestenbock,

I agree with you, this is a part I hadn't considered.

For the enum problem, I think we'll have to override the JSON encoder of the request (will solve the problem more globally than the `.value` and without regression).

For the `enabled` argument at the root, there is a second method available if you need to set it globally:

* `change_channel_preference` for a partial change on one of the channel
* `change_preference_state` to fully enabled/disable preference.

My understanding at API level is that either it's global, and therefore `enabled` at the root, or it's case by case and therefore `{"channel": {"type": channel, "enabled": channel_enabled}}`.

**Comment by ryshu** [comment]
Hum, find a better way to solve it: https://hultner.se/quickbits/2018-03-12-python-json-serializable-enum.html
