### ISSUE TITLE
Request for full Python Documentation

### ISSUE THREAD

**Issue by sahunikhil** [novuhq/novu-python#38]
**Is your feature request related to a problem? Please describe.**
Python Documentation contains only one method i.e for triggering event. Users will want to see python code for creating subscriber, topic, digest,etc.

**Describe the solution you'd like**
If Python SDK is already developed then it should be documented in GitHub as well as in Novu Website API Reference Documentation. At least in GitHub. If not developed then must be developed for utility.

**Describe alternatives you've considered**
None

**Additional context**
All the best and thanks for providing Novu <3.

**Comment by ryshu** [comment]
Hi @sahunikhil,

I'm not sure to understand the request here.
A documentation is available in parallel with the repository here and provides all the references with the various fields, methods and so on. https://novu-python.readthedocs.io/en/latest/index.html

As for the "how to" part, this documentation doesn't claim to explain everything yet, as the API is still subject to change (version 0.Y.Z on the main project).
