### ISSUE TITLE
Docs: Quickstart Guide on Getting Started with Novu Python

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-python#39]
We currently have quickstart guides in different languages.

We need a Python Quickstart. There's a template to follow below:

[Get Started with PHP](https://docs.novu.co/overview/quickstart/get-started-with-php)

**Comment by ankur0904** [comment]
@unicodeveloper Can I contribute to this issue?

**Comment by unicodeveloper** [comment]
Yes please. @ankur0904 When would you like to start?

cc @iampearceman

**Comment by ankur0904** [comment]
@unicodeveloper I would like to start from tomorrow.

**Comment by kunjshukla** [comment]
Hey, I would like to contribute to this issue, please can you assign me

**Comment by unicodeveloper** [comment]
Hey @kunjshukla I have assigned @ankur0904 to this issue. 

If you'd like to contribute to the docs, I can assign you to another issue if you don't mind. What do you think?

@ankur0904 this is the link to the docs that have all the other quickstarts https://github.com/novuhq/novu/tree/main/docs/docs/overview/quickstart.

Clone the repo, cd into docs, run `npm install` and run `npm run start` to serve up the docs.

**Comment by ankur0904** [comment]
@unicodeveloper Thanks I will set up the project locally.

**Comment by unicodeveloper** [comment]
Awesome. When do you think you will be done? @ankur0904 ETA

**Comment by ankur0904** [comment]
@unicodeveloper 8:30 am Tuesday

**Comment by unicodeveloper** [comment]
Perfecto. I will check in on you tomorrow. Thank you so much @ankur0904

**Comment by kunjshukla** [comment]
@unicodeveloper , Agreed can you assign me another issue related to docs.

**Comment by ankur0904** [comment]
@unicodeveloper I set up the project locally successfully.

![1](https://github.com/novuhq/novu-python/assets/98346896/43be6cc4-998b-41c0-bd21-8e3c3b46b1da)

**Comment by unicodeveloper** [comment]
@ankur0904 That's sweet, have you written the quickstart yet?

**Comment by ankur0904** [comment]
@unicodeveloper no I haven't written the quickstart yet!

**Comment by unicodeveloper** [comment]
Okay when should I look forward to? @ankur0904

**Comment by ankur0904** [comment]
@unicodeveloper within 2-3 days.

**Comment by ankur0904** [comment]
@unicodeveloper  Update till now.


![Screenshot from 2023-07-06 00-54-06](https://github.com/novuhq/novu-python/assets/98346896/2bffc01f-9924-44df-b7ab-d06e80abbf10)
![Screenshot from 2023-07-06 00-54-20](https://github.com/novuhq/novu-python/assets/98346896/2834cc35-884e-4ab0-8e34-7715b9dc5a65)

**Comment by unicodeveloper** [comment]
Nice!!!! Well done.

Looking forward to the completion @ankur0904
