### ISSUE TITLE
Docs: Update Readme with code snippets examples for all the API methods

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-python#40]
Right now, we currently only have the event API trigger example in the readme.

We need all the other examples to be in the readme to enable very easy copy and paste

**Comment by J-rayX** [comment]
@unicodeveloper, can I get on this?

**Comment by unicodeveloper** [comment]
Yes, you can! Assigning this you now @J-rayX

**Comment by ryshu** [comment]
Hi @unicodeveloper,

I don't understand why we want to put those snippets in README when we have the generated documentation based on code documentation: https://novu-python.readthedocs.io/en/latest/index.html.

This will encourage SDK not to read the docs and instead ask questions about issues when some snippets while not be up-to-date.

I am more in favor of something link cookbook to explain how each method work (if needed) and a reference to generated documentation about the full usage of the API. https://novu-python.readthedocs.io/en/latest/guides/cookbook.html

The only update in the readme to do for me is to point to the documentation site

WDYT ?

**Comment by unicodeveloper** [comment]
Hey @ryshu 

The first point of contact for everyone is the readme. The docs is not immediately noticeable (because it is not in the readme) and when they finally figure that it is in the about section, they still have to dig in to figure out what parameters and methods need to be called for them to do what they need.

This week, someone offered to write the quickstart guide and we went back and forth on discord on how to simply create a subscriber.

I'm not a Python developer so I had to go dig in and try to put 1 or 2 things together to understand how to create a subscriber. He's a Python developer and he was confused on whether to use a DTO or just pass the parameters directly.

We can still do a cookbook but I want us to have copyable code snippets for everything to cater for beginners, mid-level and even non-Python developers that find out about Novu. 

I can maintain the readme and ensure they are updated if they ever need to change. But we need all the examples we can have to avoid a lot of back and forth 😄

**Comment by unicodeveloper** [comment]
@ryshu In PHP, this is how I initialize the SDK and connect to it before I call the methods.

```php
use Novu\SDK\Novu;

$novu = new Novu(<INSERT_API_KEY_HERE>);

// Trigger event
$response = $novu->triggerEvent([
    'name' => '<REPLACE_WITH_TEMPLATE_NAME_FROM_ADMIN_PANEL>',
    'payload' => ['customVariables' => 'Hello'],
    'to' => [
        'subscriberId' => '<SUBSCRIBER_IDENTIFIER_FROM_ADMIN_PANEL>',
        'phone' => '07983882186'
    ]
]);

// Create a Subscriber
$subscriber = $novu->createSubscriber([
    'subscriberId' => 'YOUR_SYSTEM_USER_ID>',
    'email' => '<insert-email>', // optional
    'firstName' => '<insert-firstname>', // optional
    'lastName' => '<insert-lastname>', // optional
    'phone' => '<insert-phone>', //optional
    'avatar' => '<insert-avatar>', // optional
]);
```

What's the sample code recipe to initialize the python SDK once and then call the methods? I can see there is a NovuConfig class but I am lost on how to use it.

The current example in the docs show that each API, e.g. EventAPI & SubscriberAPI has to take in argument of the  api novu url which I am not a fan of. Please correct me here.

**Comment by unicodeveloper** [comment]
A good example is for people like me that deal with users asking questions on GitHub and discord all the time.

I switch between several sdks trying to find snippets to add to docs, respond on Twitter and many adhoc ways of telling people how to perform specific tasks in different sdks.

I and a few others also on discord just want to be able to lift these code samples from the readme instead of having to clone and check the editor to understand how it works.

There are beginner level developers that use Novu too that just want copy and paste.

**Comment by unicodeveloper** [comment]
> What's the sample code recipe to initialize the python SDK once and then call the methods? I can see there is a NovuConfig class but I am lost on how to use it.

Please can you show the sample code / way to do this? @ryshu

**Comment by ryshu** [comment]
To sum up my thoughts, I think you can put them in the README.md, citing the documentation for more details, but you should also put them in the code directly so that the documentation is directly available to users.

For example:

![image](https://github.com/novuhq/novu-python/assets/22155261/dd96d829-c2a7-46d3-b178-3cccb67acc65)

**Comment by ryshu** [comment]
> > What's the sample code recipe to initialize the python SDK once and then call the methods? I can see there is a NovuConfig class but I am lost on how to use it.
> 
> Please can you show the sample code / way to do this? @ryshu

Should be documented in the COOKBOOK.rst
NovuConfig is a singleton, which can be reused everywhere

```python
from novu.config import NovuConfig
from novu.api import EventApi
NovuConfig.configure("https://api.novu.co", "<NOVU_API_TOKEN>")
EventApi().trigger(
     name="<YOUR_WORKFLOW_ID>",  # The workflow ID is the slug of the workflow name. It can be found on the workflow page.
    recipients="<YOUR_SUBSCRIBER_ID>",
    payload={},  # Your Novu payload goes here
)
```
If i `configure` the NovuConfig, then I don't need to reconfigure URL/TOKEN every time

**Comment by unicodeveloper** [comment]
Okay please can you add to the cookbook?

Just to reiterate:

```python
from novu.config import NovuConfig
from novu.api import EventApi

NovuConfig().configure("https://api.novu.co", "<NOVU_API_TOKEN>")

EventApi().trigger(
     name="<YOUR_WORKFLOW_ID>",  # The workflow ID is the slug of the workflow name. It can be found on the workflow page.
    recipients="<YOUR_SUBSCRIBER_ID>",
    payload={},  # Your Novu payload goes here
)
```

From the code above, you don't need to assign the config to any variable? Once `NovuConfig().configure("https://api.novu.co", "<NOVU_API_TOKEN>")` is called, will EventApi().trigger implicitly just know it has been configured for it to make the request to trigger an event? @ryshu

**Comment by ryshu** [comment]
@unicodeveloper Nope.

By default every API inherite from the BaseApi class which take provided URL, or by default URL from the config singleton.

It's how the singleton pattern work.

![image](https://github.com/novuhq/novu-python/assets/22155261/e2e983f1-d738-4bb3-91aa-985a31f066da)

See https://en.wikipedia.org/wiki/Singleton_pattern for more details

**Comment by J-rayX** [comment]
Hi @ryshu,
Following through on your conversation with @unicodeveloper:
So now, we can put the snippet examples for the methods in the README or the documentation? 
Either way, it will still be good to have sample code for the endpoints, at least for now. To aid quick adoption. 

We can do both, put a few examples in the README, then, more in the ReadTheDocs website. That's what I'd suggest.
Let me know what you think, please.

**Comment by J-rayX** [comment]
BTW,
@unicodeveloper, if the Discord server is open to the public, enthusiasts and new Novu users, I'd appreciate an invite.

**Comment by unicodeveloper** [comment]
> Hi @ryshu, Following through on your conversation with @unicodeveloper: So now, we can put the snippet examples for the methods in the README or the documentation? Either way, it will still be good to have sample code for the endpoints, at least for now. To aid quick adoption.
> 
> We can do both, put a few examples in the README, then, more in the ReadTheDocs website. That's what I'd suggest. Let me know what you think, please.

Let's do both! But readme first. @J-rayX

**Comment by unicodeveloper** [comment]
> BTW, @unicodeveloper, if the Discord server is open to the public, enthusiasts and new Novu users, I'd appreciate an invite.

Yes it's open. Join here https://discord.gg/novu

**Comment by J-rayX** [comment]
Thanks.

**Comment by J-rayX** [comment]
> > BTW, @unicodeveloper, if the Discord server is open to the public, enthusiasts and new Novu users, I'd appreciate an invite.
> 
> Yes it's open. Join here https://discord.gg/novu

Thanks.
