### ISSUE TITLE
Update packages based on this security dependabot notice

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-python#46]
https://github.com/novuhq/novu-python/security/dependabot/2

We need to update this.

**Comment by seun-beta** [comment]
Hello @unicodeveloper 

I hope you are good. The link: https://github.com/novuhq/novu-python/security/dependabot/2 redirects to a 404 page. Can you share the security alerts as an image?

**Comment by ryshu** [comment]
Hi @seun-beta and @unicodeveloper ,

I'll take care of it next week, it's not really "urgent" because it's not necessary to install this version of certifi for our users (only in development deps).

![image](https://github.com/novuhq/novu-python/assets/22155261/a00216a3-b8f5-4a89-8e6c-23c7851a2112)
