### ISSUE TITLE
Apis needed for create and delete organizations

### ISSUE THREAD

**Issue by prathapbelli** [novuhq/novu-python#49]
Currently python SDK doesn't contain apis related to organization,
Apis are needed to create novu organizations based on multiple tenants at the time of onboarding/ setting up of new tenant, so we can automate our process instead of creating them manually.

**Comment by siddythings** [comment]
@unicodeveloper Can I contribute to this issue?

**Comment by ryshu** [comment]
In fact, this functionality does not exist in the API (if I am not mistaken), so we cannot add them in the SDKs.

See https://api.novu.co/api/#/ for available API features

**Comment by unicodeveloper** [comment]
The tenants feature just became available this week in v19 on the UI. But it's not documented yet in the API. 

I'll update you when that happens @prathapbelli

**Comment by prathapbelli** [comment]
@unicodeveloper They have updated Tenants apis, are we are expecting these apis? https://api.novu.co/api#/

**Comment by unicodeveloper** [comment]
This is live now in the latest release! @prathapbelli
