### ISSUE TITLE
SubscriberApi. get() not returning credentials,  field is missing in SubscriberDto

### ISSUE THREAD

**Issue by prathapbelli** [novuhq/novu-python#52]
we are using python sdk and self hosted novu, we have api for updating subscriber credentials but we don't have api to get those updated credentials info whether credentials are stored or not.

Novu getSubscriber api is returning credentials info under channel key, but in python sdk subscriberApi.get() mnot returing the same, we dont have field defined in  SubscriberDto.

novu api response:
```
"data": [
        {
            "_id": "ffff",
            "_organizationId": "ffff",
            "_environmentId": "ffff",
            "subscriberId": "ffff",
            "email": "ffff",
            "channels": [
                {
                    "_integrationId": "fffff",
                    "providerId": "slack",
                    "credentials": {
                        "webhookUrl": "https://hooks.slack.com/services/fffffff",
                        "channel": "slack",
                        "deviceTokens": []
                    }
                }]
}]
```

**Comment by unicodeveloper** [comment]
@ryshu Please can you help with this?

@prathapbelli Please feel free to submit a PR fix for this for faster turnaround.

**Comment by prathapbelli** [comment]
@unicodeveloper added PR
https://github.com/novuhq/novu-python/pull/53

**Comment by unicodeveloper** [comment]
Okay I see the PR is still in review. Please can you fix the commit issues @prathapbelli

**Comment by ryshu** [comment]
Merged in latest release (see https://github.com/novuhq/novu-python/tree/v1.5.0)
