### ISSUE TITLE
Setup GitHub Workflow for Running Unit Tests

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-python#62]
In order to ensure the stability and reliability of our codebase, it is essential to have automated unit tests running for each push and pull request. Currently, our repository lacks a GitHub Actions workflow to run unit tests, and this needs to be addressed to maintain code quality and catch issues early.

Suggested Solution:

 1.   Create a new workflow file in .github/workflows/ directory.
        Filename: run-unit-tests.yml

2.    Configure the workflow to be triggered on every push and pull_request event to the main branch.
3.    Define job steps:
        Checkout the repository.
        Setup the environment/python runtime.
        Install dependencies.
        Run the unit tests.

**Comment by SRICHARANSIRPA** [comment]
Hi @Cliftonz.... i have experience setting up  unit test cases with jest. can i this this feature ?

**Comment by VishalS-HK** [comment]
Hello. Can I be assigned this issue?

**Comment by Cliftonz** [comment]
@VishalS-HK of course!

**Comment by ryshu** [comment]
Hello,

I don't understand this problem because it is managed by this file https://github.com/novuhq/novu-python/blob/main/.github/workflows/tests.yml

It's probably activating the execution of scripts on each push that you want to talk about?
