### ISSUE TITLE
improving bug_report.md

### ISSUE THREAD

**Issue by HarshMN2345** [novuhq/novu-python#66]
The current implementation lacks explicit handling of edge cases, potentially leading to unexpected behavior under specific conditions. This issue aims to address these scenarios and improve the robustness of the codebase.

Proposed Changes:

Handle Edge Cases: Identify and implement appropriate handling for edge cases to ensure the application behaves predictably even under unusual conditions.

Input Validation: Strengthen input validation mechanisms to prevent erroneous or unexpected data from causing issues.

Error Messaging: Enhance error messaging to provide clearer and more informative feedback to users or developers when exceptional situations occur.

Testing and Validation: Thoroughly test the modified code under various scenarios to validate that the edge cases are handled correctly.

Expected Impact:

These changes are expected to improve the overall stability and reliability of the codebase, reducing the likelihood of unexpected behavior in edge cases. Additionally, they will contribute to a more robust and resilient application.

Related Context:

Provide any additional context or information related to this issue, such as specific scenarios where edge cases may arise or any known instances of unexpected behavior.

Note to Reviewers:

Please pay special attention to the handling of edge cases and ensure that the proposed changes do not introduce new issues or regressions. Additionally, consider the impact of these changes on overall system behavior and performance.

**Comment by adhirajkar3103** [comment]
Hello. Can I be assigned this issue as a part of Hacktoberfest?

**Comment by ryshu** [comment]
Merged in https://github.com/novuhq/novu-python/tree/v1.5.0
