### ISSUE TITLE
Add Missing Methods for Integrations

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-python#70]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Integrations

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/Workflow%20groups/NotificationGroupsController_updateNotificationGroup) and add the missing ones.

- [X] List integrations
- [X] Create an integration
- [X] Get active integration
- [X] Get webhook support status for provider
- [X] Update integration
- [X] Delete integration
- [X] Set integration as primary

**Comment by fadkeabhi** [comment]
@Cliftonz I just checked. The swagger contains 9 endpoints and in SDK only 7 are implemented.
I would like to work on implementing remaining 2 endpoints in this SDK. Can you assign it to me.

**Comment by Cliftonz** [comment]
@fadkeabhi  Of course

**Comment by fadkeabhi** [comment]
Hey @Cliftonz i was working on integrating  /v1/integrations/in-app/status 
and I am not sure what does this endpoint returns. as swagger UI is not showing any sample response and when i try to execute it with swagger I am getting an 401 error.
![image](https://github.com/novuhq/novu-python/assets/31249309/297574d4-db70-4629-9c79-c1bb4bb4bbc7)
Can you help me with its sample response.

**Comment by fadkeabhi** [comment]
@Cliftonz I have created an PR here https://github.com/novuhq/novu-python/pull/81. Can you take a look at it. In this PR I have implemented a method setPrimary only. as no additional information of /v1/integrations/in-app/status is available.

**Comment by Cliftonz** [comment]
@davidsoderberg Could you give some insight into the above?

**Comment by davidsoderberg** [comment]
Yes, @fadkeabhi that endpoint is not public and should not be in the sdk. I have created an pr to hide them in the api reference: https://github.com/novuhq/novu/pull/4406

**Comment by ryshu** [comment]
Closed since "set_primary" as been merged in alpha
