### ISSUE TITLE
Add Missing Methods for Layouts

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-python#72]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Layouts

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/Workflow%20groups/NotificationGroupsController_updateNotificationGroup) and add the missing ones.

**Comment by jvmazagao** [comment]
@Cliftonz Is just update with the new version of the sdk correct? I can do this. Please assign to me

**Comment by Cliftonz** [comment]
@jvmazagao This is to add the new endpoints for the layouts which may or may not already be in this sdk.
https://api.novu.co/api#/Layouts

**Comment by sumitsaurabh927** [comment]
@jvmazagao still wanna work on it?

**Comment by Yash-sudo-web** [comment]
Hey @sumitsaurabh927, Can i work on this?

**Comment by unicodeveloper** [comment]
This is the API reference documentation for Layouts - https://docs.novu.co/api-reference/layouts/layout-creation

**Comment by unicodeveloper** [comment]
Assigning this to you now @Yash-sudo-web

**Comment by unicodeveloper** [comment]
Assigned @Yash-sudo-web 🌟

**Comment by Yash-sudo-web** [comment]
Hey, i checked the swagger and SDK, Filter layouts seems to be missing, i'd work on it right away.

**Comment by unicodeveloper** [comment]
Awesome, I'll close this now. Maybe you can check other issues and see if there's any that is missing you can pick up @Yash-sudo-web
