### ISSUE TITLE
Add Missing Methods for Inbound Parse

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-python#73]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Inbound Parse

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/Workflow%20groups/NotificationGroupsController_updateNotificationGroup) and add the missing ones.

**Comment by srikanth597** [comment]
/v1/inbound-parse/mx/status

the above Route also has been already implemented , hence this can be closed
