### ISSUE TITLE
Add Missing Methods for Changes

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-python#75]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Changes

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/Workflow%20groups/NotificationGroupsController_updateNotificationGroup) and add the missing ones.

**Comment by srikanth597** [comment]
I see all the methods have been implemented, hence we can close this issue
