### ISSUE TITLE
Add Missing Methods for Blueprints

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-python#79]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Blueprints

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/Workflow%20groups/NotificationGroupsController_updateNotificationGroup) and add the missing ones.

**Comment by ayrotideysarkar** [comment]
I want to try this one

**Comment by Yash-sudo-web** [comment]
hey @unicodeveloper, can i work on this issue?

**Comment by unicodeveloper** [comment]
I just checked and I can see the Blueprints feature and methods are not available in this SDK yet. So I will assign to you @Yash-sudo-web 

These are the methods and API reference for you to use.
- Get Blueprints group by Category - https://docs.novu.co/api-reference/get-v1blueprintsgroup-by-category
- Get Blueprints - https://docs.novu.co/api-reference/get-v1blueprints

**Comment by unicodeveloper** [comment]
Assigned now! @Yash-sudo-web ⭐
