### ISSUE TITLE
Enable renovate on this repository

### ISSUE THREAD

**Issue by ryshu** [novuhq/novu-python#85]
@unicodeveloper @Cliftonz It would be great if you could see internally to activate the renovate bot on the repository: https://docs.renovatebot.com/getting-started/installing-onboarding/#hosted-githubcom-app

See https://docs.renovatebot.com/ for more details

It seems to me that there are quite a few updates that would automatically be proposed by the latter.

A configuration that works well with the latter:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    ":enablePreCommit"
  ],
  "baseBranches": [
    "alpha"
  ]
}
```

**Comment by HarshMN2345** [comment]
can i be assigned for this issue?

**Comment by ryshu** [comment]
I'm sorry 

Since you haven't admin access, you will not be able to handle it

**Comment by Cliftonz** [comment]
@ryshu I will take at look at this

**Comment by scopsy** [comment]
@ryshu I have enabled the app on renovate, is a config still needed to be added to the codebase?

**Comment by ryshu** [comment]
> @ryshu I have enabled the app on renovate, is a config still needed to be added to the codebase?

I'm in the process of doing this, but yes there are some modifications to make to have a renovate behavior that looks like what we want.

Additionally, the bot only works if the file is at the root of the project.
